added volume mounts to extractors
clowder-framework/clowder-helm pull request #9
Opened 2023-06-28 16:58 UTC by minump

Added volume mounts to extractors using extraVolumes and extraVolumeMounts options in helm chart

2023-06-28 20:26 UTC, minump commented
@robkooper ready for review.

2023-08-16 19:45 UTC, robkooper requested changes
small tweaks so we can release.

2023-08-16 19:45 UTC, robkooper commented on values.yaml
> +    extraVolumes:
can you add `[]` to this, so it knows it needs to be an arrray.

2023-08-16 19:45 UTC, robkooper commented on CHANGELOG.md
> +## Unreleased
bump patch version here and in `chart.yaml`

2023-08-16 21:03 UTC, minump commented on values.yaml
> +    extraVolumes:
updated.

2023-08-16 21:04 UTC, minump commented on CHANGELOG.md
> +## Unreleased
updated to 0.16.7

2023-08-16 21:04 UTC, minump commented
Ready for review @robkooper

2023-08-21 02:39 UTC, robkooper approved these changes

2023-08-21 02:39 UTC, merged